### ISSUE TITLE
Can't get pam_wtid to work on Ventura

### ISSUE THREAD

**Issue by psaintemarie** [inickt/pam_wtid#2]
Hi!

Trying to setup `pam_witd` on macOS 13.0 Ventura and getting an error when trying to use sudo after:

```
❯ make enable
sudo mkdir -p /usr/local/lib/pam
sudo install -b -o root -g wheel -m 444 pam_wtid.so /usr/local/lib/pam/pam_wtid.so.2
sudo sed -E -i ".bak" "1s/^(#.*)$/\1\nauth       sufficient     pam_wtid.so/" "/etc/pam.d/sudo"
❯ sudo vim /etc/pam.d/sudo
sudo: unable to initialize PAM: No such file or directory
```

This what the `sudo` file look like:
```
❯ cat /etc/pam.d/sudo
# sudo: auth account password session
auth       sufficient     pam_wtid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
```

Obviously `make disable` fails because of the above `sudo` error.
I can revert by booting into recovery (M1 here).

Some info:

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.0
BuildVersion:		22A380
❯ xcode-select -p
/Applications/Xcode-14.1.0.app/Contents/Developer
```

Let me know if you need more info.

**Comment by inickt** [comment]
Thank you for reporting! I haven't yet updated to Ventura yet, will do so soon so I can investigate. Sorry for breaking your system, glad you know your way around recovery tools 😛. I'll try and think about how to make this safely roll back if it doesn't work, and maybe add a spot in the README for validated versions? Maybe some GHA runners too to test?

**Comment by fj-perez** [comment]
Hi guys:

5 months ago , this tiny little bug in **patch.py** also broke my system. I can confirm that this is only affecting M1 machines. 

When **attempt_patch** is executed, the result in line 39

` call_instr_match = re.search(objdump_call_regex, dissassembly, flags=re.MULTILINE)`

is **TRUE** for both X86 and ARM.

This results in a "double patched" **pam_wtid.so** file:

```
❯python3 patch.py pam_tid.so.2 pam_wtid.so
Opening pam_tid.so.2
Found x86_64 call instruction: e86b0b0000
Patched x86_64: be01000000 to be04000000
Found arm64e call instruction: d6020094
Patched arm64e: 21008052 to 81008052
Writing patch to pam_wtid.so

```

**Comment by inickt** [comment]
I am still looking into this. As far as I can tell, the patching is still working correctly. The issue seems to be something code signing related on Ventura, it seems it doesn't like adhoc signatures for PAM modules anymore. I can't find anything about this online so that seems surprising.

@fj-perez After double checking some things, that looks like it is working as expected. Apple ships all of its binaries as fat universal binaries (in theory you can take an Apple Silicon macOS install and boot it on Intel, and vice versa). You can confirm this with 
```
❯❯❯ lipo -archs /usr/lib/pam/pam_tid.so.2
x86_64 arm64e
```

**Comment by inickt** [comment]
Also FYI, if you have a bad PAM module configuration, you can open Finder to `/usr/lib/pam/` and `/usr/local/lib/pam/`, and then drag/rename `pam_tid.so.2` to `pam_wtid.so.2`. Finder has its own permissions logic so you can bypass a bad sudo config.

**Comment by VincentSit** [comment]
Same issue here. Hope that this can be fixed at some point in the future.
```
sudo: unable to initialize PAM: No such file or directory
```

```
➜  pam_wtid git:(main) sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
➜  pam_wtid git:(main) xcode-select -p
/Applications/Xcode-14.3.0.app/Contents/Developer
```

I easily recovered sudo through [this tutorial](https://unix.stackexchange.com/a/636983/179720).

**Comment by inickt** [comment]
FYI this is working as-is on Sonoma 14.4.1. I am not sure why this had issues/when the bug might have been fixed, but I am not having any issues running it now.

Let me know if you see otherwise.

**Comment by inickt** [comment]
I added a safety step to `make enable` to test `sudo` to make sure authentication works. If it fails it will unwind the uninstall (which should always work since `sudo` was already authenticated), which should hopefully help with the mess of fixing a broken module.
